### ISSUE TITLE
IS-05: Automate remaining workshop/interop checklist items for Connection API implementations

### ISSUE THREAD

**Issue by garethsb-sony** [bbc/nmos-testing#32]
Based on the most recent interop checklists, the following items remain to be automated if possible.
NB: Not all test cases are applicable for all Device Classes.

### AMWA NMOS Connection Management (IS-04) Checklist
Version 1.2 (2nd July 2018)
#### Section 1: API Implementations

- [x] **1.1** Connection Management API structure matches the spec.
- [x] **1.2** All API endpoints implement the correct methods (GET, PATCH etc.)
- [x] **1.3** A transport file (e.g SDP) can be staged to the receiver API directly
- [x] **1.4** The transport parameters in the transport file automatically propagate to the receiver’s staged transport parameters
- [x] **1.5** Immediate activations can be called on the API
- [x] **1.6** Relative offset and absolute offset activations can be called on the API
- [x] **1.7** When activation occurs staged transport parameters transition to active
- [x] **1.8** For relative and absolute offset activations the transition of parameters occurs at the correct time offset.
- [ ] **1.9** During activation all “auto” entries are translated to their actual values
- [ ] **1.10** During the time between a delayed activation being requested and it occurring, any attempt to alter staged transport files or parameters results in an HTTP 423 (locked).
- [ ] **1.11** The sender’s active transport file endpoint returns an HTTP 200 response containing the transport file.
- [x] **1.12** The API rejects any requests that do not match the relevant schema with an HTTP 400 response code
- [ ] **1.13** If a transport file and transport parameter set are PATCHed to staged simultaneously the content of the transport parameters takes precedence over the content of the transport files.
- [x] **1.14** The keys in the the constraints endpoint mirror the keys of the transport parameters on the staged endpoint
- [ ] **1.15** At the point of activation the 'version' attribute of the relevant IS-04 Sender or Receiver is incremented.
- [ ] **1.16** Receivers which do not support 2022-7 can stage transport parameters for the primary leg only when receiving a 2022-7 format transport file

**Comment by garethsb-sony** [comment]
Wr.t. **1.15** At the point of activation the 'version' attribute of the relevant IS-04 Sender or Receiver is incremented, that's one part of #16.

**Comment by garethsb-sony** [comment]
I think some of the remaining tasks and additional bits identified in comments have now been implemented?

**Comment by garethsb** [comment]
**1.9** was resolved by https://github.com/AMWA-TV/nmos-testing/pull/497

**Comment by peterbrightwell** [comment]
This issue has been labelled as an enhancement and captured on the internal roadmap which will determine when resources can be allocated to address it.
