### ISSUE TITLE
IS-05: Automate remaining workshop/interop checklist items for the Bulk Interface

### ISSUE THREAD

**Issue by garethsb-sony** [bbc/nmos-testing#34]
Based on the most recent interop checklists, the following items remain to be automated if possible.
NB: Not all test cases are applicable for all Device Classes.

### AMWA NMOS Connection Management (IS-05) Checklist
Version 1.2 (2nd July 2018)
#### Section 3: Bulk Interface

- [x] **3.1** The bulk interface is exposed as an endpoint
- [x] **3.2** Changes made to staged parameters in the bulk interface are correctly reflected in the single interface.
- [x] **3.3** Activations carried out on the bulk interface result in the activation of staged parameters
- [ ] **3.4** If an individual sender/receiver rejects the request (i.e returns a 400/500 series response) the status code is reflected in the JSON response, but the response code for the bulk request is still 200.

**Comment by simonrankine** [comment]
3.4 - Send a deliberately out-of-schema request on one part of the schema, check that the result is still 200 (hard to make a 500 occur, but we can hope that it will behave in the same way as for a 400 series error).
