### ISSUE TITLE
IS-05: Automate remaining workshop/interop checklist items  for SMPTE 2022-7 Operation

### ISSUE THREAD

**Issue by garethsb-sony** [bbc/nmos-testing#35]
Based on the most recent interop checklists, the following items remain to be automated if possible.
NB: Not all test cases are applicable for all Device Classes.

### AMWA NMOS Connection Management (IS-05) Checklist
Version 1.2 (2nd July 2018)
#### Section 4: SMPTE 2022-7 Operation

This section only applied to API servers making use SMPTE 2022-7 “dual legged” operation.

- [ ] **4.1** Staged and active transport parameters are able to have two “legs” with different parameter sets for each
- [ ] **4.2** During activations both “legs” are activated simultaneously
- [ ] **4.3** When operating with SMPTE 2022-7, senders provide transport files compliant with SDP group semantics (see VSF TR-04)
- [ ] **4.4** Transport files specifying parameters for both legs (as per VSF TR-04) are correctly parsed by receivers and applied to staged transport parameters
- [ ] **4.5** When a SMPTE 2022-7 receiver is activated with a SDP file that only specifies one leg it only populates one leg of the transport parameters, and returns the other leg to null/default values.
- [ ] **4.6** Node API correctly advertises two interface_bindings for Senders and Receivers which are 2022-7 capable.
- [ ] **4.7** Constraints endpoint has two separate elements with constraints for each leg, even if they are identical.

**Comment by garethsb-sony** [comment]
W.r.t. **4.6** Node API correctly advertises two interface_bindings for Senders and Receivers which are 2022-7 capable, this may form part of #16.

**Comment by simonrankine** [comment]
Again - the test suite should ideally ask whether the device supports 2022-7 mode...

4.1 - Stage parameters to each leg if present, check that they can change independently
4.2 - Check that transport params progress to /active from both legs
4.3 - Download SDP file from /transportfile of senders operating in 2022-7 mode and check the SDP file
4.4 - Pass a mock SDP file into the receiver and check that transport params propagate correctly into /staged
4.5 - Pass SDP file that should cause this behaviour, and check transport params in /stgaed
4.6 - Should be a simple get from the Node API, but I guess you'd have to go back to the registry to find it...
4.7 Check that the number of entries in the /constraints array is the same as the number of entries in the /staged and /active endpoints

**Comment by simonrankine** [comment]
IMHO 4.7 is satisfied by IS0501 tests 38 and 39

**Comment by garethsb-sony** [comment]
Regarding 4.5, I think the spec says only that ``rtp_enabled`` should be set to ``false``?

**Comment by garethsb-sony** [comment]
Regarding 4.7, @simonrankine, do you think we should also be checking the same transport parameters are listed in each leg of the constraints and staged and active?

**Comment by peterbrightwell** [comment]
This issue has been labelled as an enhancement and captured on the internal roadmap which will determine when resources can be allocated to address it.
