### ISSUE TITLE
IS-05: Automate remaining workshop/interop checklist items for FEC and RTCP

### ISSUE THREAD

**Issue by garethsb-sony** [bbc/nmos-testing#36]
Based on the most recent interop checklists, the following items remain to be automated if possible.
NB: Not all test cases are applicable for all Device Classes.

### AMWA NMOS Connection Management (IS-05) Checklist
Version 1.2 (2nd July 2018)

#### Section 5: FEC and RTCP

These tests only apply to servers making use of FEC and/or RTCP parameters.

- [ ] **5.1** Where FEC is in use, FEC parameters are exposed in staged and active parameter sets
- [ ] **5.2** Where FEC is in use, FEC parameters are represented in the constraints endpoint as per the spec. examples
- [ ] **5.3** Where RTCP is in use, RTCP parameters are exposed in staged and active parameter sets
- [ ] **5.4** Where RTCP is in use, RTCP parameters are represented in the constraints endpoint as per the spec. examples

**Comment by simonrankine** [comment]
Ideally the test suite should ask if it should expect FEC/RTCP parameters to be present and test accordingly. We should also test that these parameters get extracted from SDP files. Should be possible to automate though.
