### ISSUE TITLE
IS-05: Automate remaining workshop/interop checklist items for SDP Files

### ISSUE THREAD

**Issue by garethsb-sony** [bbc/nmos-testing#38]
Based on the most recent interop checklists, the following items remain to be automated if possible.
NB: Not all test cases are applicable for all Device Classes.

### AMWA NMOS Connection Management (IS-05) Checklist

Version 1.2 (2nd July 2018)

#### Section 7: SDP Files

- [ ] **7.1** SDP file and /transportfile endpoint must pass a sdpoker test, run with default settings: https://github.com/Streampunk/sdpoker
- [ ] **7.2** Receivers should tolerate SDP fmtp lines which:
  - Have no additional termination character before the carriage return.
  - Use a semicolon ';' before the carriage return.
  - Use a semicolon and space '; ' before the carriage return.
- [ ] **7.3** Receivers should tolerate SDP files that contain attribute parameters detailing the mapping of RTP header extensions.

**Comment by simonrankine** [comment]
7.1 - Download SDP file from all /transportfile endpoints, run against SDPoker
7.2 - Present receivers with an SDP file with each permutation and check all parameters propagate to the transport params correctly (obviously can't test whether it subscribes to the stream correctly though).
7.3 - Present receivers with an SDP with header extensions - again, can't check from a 2110 point of view but transport params should propagate through at least.
